title: Serenade Wind
email: serenadewind@gmail.com
locale: "en-US"
ampdir: amp
netlify_cms: true
description: 
baseurl: ''
url: 'https://serenadewind.com'
logo: /images/rjs-logo.png
background_image: "serenade-wind-background"

# SEO 
social:
  name: Serenade Wind
  links:
    - https://twitter.com/serenade_wind
    - https://www.facebook.com/serenade.wind.adventures
    - https://www.instagram.com/serenade.wind
    - https://reddit.com/user/serenade_wind

facebook:
  publisher: https://www.facebook.com/serenade.wind.ventures

markdown: CommonMark
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/dark.css"
read_time: true
words_per_minute: 200
google_fonts:
  - name: "Princess Sofia"
    weights: "400,500,600"
  - name: "Montez"
  - name: "Poiret One"
    weights: "400,500,600"
jekyll-archives:
  enabled: 
    - month
  layouts: 
    month: monthly-content
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-commonmark
  - jekyll-include-cache
exclude: 
  - jekyll-image-gallery-example
  - node_modules
  - tools
  - image-resize.py
  - image-file-undo.py
  - package.json
  - Gemfile
  - Gemfile.lock
  - _drafts
  - .jekyll-cache
include:
  - _redirects #netfly redirect
  - _headers

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"